In [1]:
# Impor Pustaka NumPy dan Definisikan Matriks
import numpy as np

# Definisikan sistem persamaan linear dalam bentuk matriks augmented
SPL = np.array([[2, 3, -1, 5],
                [4, 4, -3, 3],
                [-2, 3, -1, 1]])

print("Sistem Persamaan Linear matriks adalah: \n", SPL)

Sistem Persamaan Linear matriks adalah: 
 [[ 2  3 -1  5]
 [ 4  4 -3  3]
 [-2  3 -1  1]]


In [20]:
# Fungsi eliminasi Gauss
def eliminasi_gauss(matriks):


  n = len(matriks)
  for i in range(n):
      # Cari elemen pivot terbesar pada kolom i ke bawah
      max_row = i
      for k in range(i+1, n):
          if abs(matriks[k][i]) > abs(matriks[max_row][i]):
              max_row = k
      # Tukar baris i dengan baris max_row (jika perlu)
      matriks[[i, max_row]] = matriks[[max_row, i]]
      # Eliminasi elemen di bawah diagonal utama
      for j in range(i+1, n):
          faktor = matriks[j][i] / matriks[i][i]
          for k in range(i, n+1):
              matriks[j][k] -= faktor * matriks[i][k]
  return matriks

In [11]:
# Memanggil Fungsi Eliminasi Gauss
SPL = eliminasi_gauss(SPL)

print("\nMatriks setelah eliminasi Gauss: \n", SPL)


Matriks setelah eliminasi Gauss: 
 [[ 4  4 -3  3]
 [ 0  5 -2  2]
 [ 0  0  0  2]]


In [16]:
# Substitusi balik untuk mendapatkan solusi
n = len(SPL)
x = np.zeros(n)
x[n-1] = SPL[n-1][n] / SPL[n-1][n-1]
for i in range(n-2, -1, -1):
    sum = 0
    for j in range(i+1, n):
        sum += SPL[i][j] * x[j]
    x[i] = (SPL[i][n] - sum) / SPL[i][i]

print("\nSolusi sistem persamaan linear:")
for i in range(n):
    print(f"x{i+1} = {x[i]}")


Solusi sistem persamaan linear:
x1 = nan
x2 = inf
x3 = inf


<ipython-input-16-af7a9f8164cd>:4: RuntimeWarning: divide by zero encountered in scalar divide
  x[n-1] = SPL[n-1][n] / SPL[n-1][n-1]
<ipython-input-16-af7a9f8164cd>:8: RuntimeWarning: invalid value encountered in scalar add
  sum += SPL[i][j] * x[j]
